package com.example.imageviewer.view.composeview.values

import androidx.compose.ui.unit.dp

val OPENED_IMAGE_PADDING = 16.dp
val OPENED_IMAGE_BUTTON_DIMEN = 60.dp
val OPENED_IMAGE_BUTTON_MARGIN = 8.dp


val BACKGROUND_PLAN_ELEVATION = 0.dp
val CONTENT_PLAN_ELEVATION = 4.dp
val CONTROL_PANEL_PLAN_ELEVATION = 8.dp
val FIRST_PLAN_ELEVATION = 12.dp

val PROGRESS_BAR_STROKE_WIGHT = 12.dp

val SMALL_SHAPE_ROUND_CORNED = 4.dp
val MEDIUM_SHAPE_ROUND_CORNED = 0.dp
val LARGE_SHAPE_ROUND_CORNER = 16.dp

